steps:
# pull image from artifact registry for caching
- name: 'gcr.io/cloud-builders/docker'
  id: 'pull-image'
  entrypoint: 'bash'
  args:
      - '-c'
      - 'docker pull ${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:latest || exit 0'

# build image
- name: 'gcr.io/cloud-builders/docker'
  id: 'build-image'
  args: [ 'build', '-f', 'Dockerfile', '-t', '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:latest', '.' ]

images:
  - ${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}

options:
  machineType: 'E2_HIGHCPU_8'